# DC2 Spine Switches
spine:
  defaults:
    platform: vEOS-lab
    bgp_as: 65002
    loopback_ipv4_pool: 192.168.101.0/24
    mlag: false
  nodes:
    - name: dc2-spine1
      id: 21
      mgmt_ip: 192.168.0.211/24
    - name: dc2-spine2
      id: 22
      mgmt_ip: 192.168.1.212/24

# Leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    bgp_as: 65200-65299 # Gives a range which will be auto-assigned
    platform: vEOS-lab
    loopback_ipv4_pool: 192.168.101.0/24 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 192.168.202.0/24 # This is loopback1 (VTEP)
    uplink_interfaces: [Ethernet3, Ethernet4] # Leaf uplinks
    uplink_switches: [dc2-spine1, dc2-spine2] # Where the leaf uplinks go
    uplink_ipv4_pool: 192.168.203.0/24 # For the p2p interfaces to chopped up into /31s
    mlag_interfaces: [Ethernet1, Ethernet2] # MLAG peer link
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_mode: mstp # Spanning Tree is still enabled even in EVPN setups
    spanning_tree_priority: 16384 
    mlag: true # By default, use MLAG
  node_groups: 
    - group: mlag1
    # bgp_as is configured automatically from the range, but can be overriden
      nodes:
        - name: dc2-leaf1
          id: 23
          mgmt_ip: 192.168.0.201/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: dc2-leaf2
          id: 24
          mgmt_ip: 192.168.0.202/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
    - group: mlag2
      #bgp_as: 65250 # Overriden automatic allocation for this Leaf pair
      nodes:
        - name: dc2-leaf3
          id: 25
          mgmt_ip: 192.168.0.203/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        - name: dc2-leaf4
          id: 26
          mgmt_ip: 192.168.0.204/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6]
    - group: borderleafs
      bgp_as: 65250 # Overriden automatic allocation for BorderLeafs
      nodes:
        - name: dc2-borderleaf1
          id: 27
          mgmt_ip: 192.168.0.205/24
          uplink_switch_interfaces: [Ethernet7, Ethernet7]
          evpn_gateway:
            # Define remote peers of the EVPN VXLAN Gateway. If the hostname can be found in the inventory, ip_address and BGP ASN will be automatically populated. Manual override takes precedence. If the peer's hostname can not be found in the inventory, ip_address and bgp_as must be defined.
            remote_peers:
              - hostname: dc1-borderleaf1
        - name: dc2-borderleaf2
          id: 28
          mgmt_ip: 192.168.0.206/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
          evpn_gateway:
            # Define remote peers of the EVPN VXLAN Gateway. If the hostname can be found in the inventory, ip_address and BGP ASN will be automatically populated. Manual override takes precedence. If the peer's hostname can not be found in the inventory, ip_address and bgp_as must be defined.
            remote_peers:
              - hostname: dc1-borderleaf2
